[supervisord]
nodaemon=true
loglevel=info

[program:step-ca]
command=step-ca /home/step/config/ca.json
autostart=true
autorestart=true
stderr_logfile=/var/log/step-ca.err.log
stdout_logfile=/var/log/step-ca.out.log
user=root 

[program:certificate-creation]
command=/scripts/generate_cert.sh
autostart=true
autorestart=true
stderr_logfile=/var/log/certificate-creation.err.log
stdout_logfile=/var/log/certificate-creation.out.log
