server {
    listen 80;
    server_name localhost;

    # Enable Gzip Compression
    gzip on;
    gzip_types text/plain application/json application/javascript text/css;

    # Root folder where your built React app is served
    root /usr/share/nginx/html;

    # Ensure index.html is served as the default file
    index index.html;

    # Serve the application and prevent caching for all files
    location / {
        try_files $uri /index.html;

        # No-cache headers
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        add_header Pragma "no-cache";
        add_header Expires "0";
    }

    # Set Cache-Control Headers
    location ~* \.(?:css|js|jpg|jpeg|gif|png|svg|ico|woff2?)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public, max-age=15778463";
    }

    # Disable caching for static assets (e.g., JS, CSS, images)
    # location ~* \.(?:css|js|json|xml|png|jpg|jpeg|gif|ico|woff2?|ttf|eot|svg)$ {
    #     try_files $uri =404;

    #     add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    #     add_header Pragma "no-cache";
    #     add_header Expires "0";

    #     access_log off;
    # }

    # Uncomment if you have a backend service for APIs
    # location /api/ {
    #     proxy_pass http://backend_service;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    #     # No-cache headers
    #     add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    #     add_header Pragma "no-cache";
    #     add_header Expires "0";
    # }
}
