# rabbitmq.conf

# Set up SSL
listeners.ssl.default = 5671
ssl_options.cacertfile = /etc/rabbitmq/ssl/ca.crt
ssl_options.certfile = /etc/rabbitmq/ssl/fullchain.server.crt
ssl_options.keyfile = /etc/rabbitmq/ssl/server.key
ssl_options.verify = verify_peer
ssl_options.fail_if_no_peer_cert = true
ssl_options.versions.1 = tlsv1.2
ssl_options.versions.2 = tlsv1.3
handshake_timeout = 20000

# Set the memory high watermark
vm_memory_high_watermark.relative = 0.6
disk_free_limit.absolute = 200MB

# Set up management
management.listener.port = 15672
management.listener.ssl = false

# Log level
log.console.level = debug
